{
 "title": "Srch Presto",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(presto_cluster_active_workers, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(presto_cluster_active_workers{job=\"$job\"}, instance)"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(presto_cluster_active_workers{job=\"$job\", instance=\"$instance\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "ACTIVE WORKERS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "presto_cluster_active_workers{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "RUNNING QUERY",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_running_queries{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU TIME/SEC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(presto_cluster_total_cpu_time_secs{job=~\"$job\", instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "ReservedMemory(GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_reserved_memory{job=~\"$job\", instance=~\"$instance\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "QUEUED QUERIES",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_queued_queries{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "KROWS/SEC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(presto_cluster_total_input_rows{job=~\"$job\",instance=~\"$instance\"} [2m])) / 1000"
    }
   ]
  },
  {
   "title": "KBYTES/SEC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(presto_cluster_total_input_bytes{job=~\"$job\",instance=~\"$instance\"} [2m])) / 1024"
    }
   ]
  },
  {
   "title": "BLOCKED QUERIES",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "presto_cluster_blocked_queries{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "实时SQL监控",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(queryId, state, scheduled, query, queuedTime, elapsedTime, executionTime, totalDrivers, rawInputDataSize, cumulativeUserMemory, PeakUserMemoryReservation, totalCpuTime, totalScheduledTime) (presto_cluster_querys{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  }
 ]
}